### ISSUE TITLE
Same events with same EventId writes to same stream (expected not)

### ISSUE THREAD

**Issue by iRatkin** [nicdex/node-eventstore-client#85] opened 2019-07-29 11:05 UTC
**Describe the bug**
Hello. I used **node-eventstore-client** (https://github.com/nicdex/node-eventstore-client) for TCP connection to EventStore server.
In my task i used **md5-to-uuid** for creating EventId based on event data.
Well, if i use appendToStream with **ExpectedVersion.any**, the same events with same EventId will record in the same stream. 

If i use another ExpectedVersion (noStream, streamExists, integer etc, like in documentation below https://eventstore.org/docs/dotnet-api/optimistic-concurrency-and-idempotence/index.html ), the error WrongExpectedVersion reproduce. Picture with error below!

![Screenshot 2019-07-29 at 12 57 02](https://user-images.githubusercontent.com/8961451/62043411-91f4e280-b200-11e9-9f86-23579f79a1da.png)

My code below:
![Screenshot 2019-07-29 at 13 01 19](https://user-images.githubusercontent.com/8961451/62043577-00d23b80-b201-11e9-83b5-92eef009bc71.png)

**To Reproduce**

1. Make docker image eventstore/eventstore:release-4.1.2
2. Run docker image, post events with same body and EventId to the same stream

**Expected behavior**
Second event will not write to stream

**Actual behavior**
Second event will write to stream with same eventId.

The same problem with [https://github.com/EventStore/EventStore/issues/1949](url), but issue was closed

**Comment by nicdex** [comment] 2019-07-31 00:09
This is not a client issue. The client is passing all those values to the server via the Tcp command. If the server is saving events with same eventId in a stream then it's an EventStore bug.

**Comment by nicdex** [comment] 2019-08-03 05:10
I was curious I did test the behavior from the nodejs client vs the .net client. 
It does work properly with the .net client.
This is puzzling as the nodejs client was ported from the .Net one and also like I said parameters are passed to the server, so I am unsure why the behavior is different.
Will investigate.

**Comment by nicdex** [comment] 2019-08-03 05:36
Just published 0.2.13 should be working now. It was a protobufjs issue.

**Comment by nicdex** [comment] 2019-08-03 06:14
Actually it had nothing to do with the protobuf. I found the issue IS server related.
They say that the eventId is unique per stream, but it is not the case when using expected version any.
For some reason when using expected version any, if you re-use the same eventId that already exists in another stream the event will be saved.

**Comment by iRatkin** [comment] 2019-08-05 11:23
@nicdex well , thanks for your change!
It is really not a protobuf problem, i think. I did a tests after update to 0.2.13 version and system went same road (pics below, same events, same stream)

**Comment by iRatkin** [comment] 2019-08-05 11:24
![Screenshot 2019-08-05 at 13 21 19](https://user-images.githubusercontent.com/8961451/62461153-456f5100-b784-11e9-90aa-3b4690f45a62.png)
![Screenshot 2019-08-05 at 13 21 10](https://user-images.githubusercontent.com/8961451/62461180-5e780200-b784-11e9-9d0b-1d4bb8487005.png)

**Comment by iRatkin** [comment] 2019-08-05 11:52
@nicdex well, if i send same events throw HTTP request, they behave expected way: only first event were writed

**Comment by nicdex** [comment] 2019-09-22 19:57
Closing this as this is not an issue with the client.
It's a "bug" with the EventStore. Make sure the eventId is unique across all the streams and it should work fine.

**Closed by nicdex** 2019-09-22 19:57 UTC
